# DSBDA Group B A1
Perform the following operations using Python on the Facebook metrics data sets
a. Create data subsets
b. Merge Data
c. Sort Data
d. Transposing Data
e. Shape and reshape Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df = df.drop('Parch', 1)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.shape

(891, 11)

# Subset


In [7]:
d_f = df[1:10][0:5]

In [8]:
d_f

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

             Ticket     Fare Cabin Embarked  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  
5            330877   8.4583   NaN        Q

# Merge Data

In [9]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display(df1, df2)

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [10]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [12]:
pd.wide_to_long

<function pandas.core.reshape.melt.wide_to_long(df: 'DataFrame', stubnames, i, j, sep: str = '', suffix: str = '\\d+') -> 'DataFrame'>

# Melt Function

In [11]:
pd.melt(df3, id_vars=['employee'], value_vars=['group','hire_date'] )

employee   variable        value
0      Bob      group   Accounting
1     Jake      group  Engineering
2     Lisa      group  Engineering
3      Sue      group           HR
4      Bob  hire_date         2008
5     Jake  hire_date         2012
6     Lisa  hire_date         2004
7      Sue  hire_date         2014

# Sort Data

In [13]:
df.sort_values(by=['Survived'])

PassengerId  Survived  Pclass                               Name     Sex  \
0              1         0       3            Braund, Mr. Owen Harris    male   
519          520         0       3                Pavlovic, Mr. Stefo    male   
521          522         0       3                    Vovk, Mr. Janko    male   
522          523         0       3                 Lahoud, Mr. Sarkis    male   
524          525         0       3                  Kassem, Mr. Fared    male   
..           ...       ...     ...                                ...     ...   
546          547         1       2  Beane, Mrs. Edward (Ethel Clarke)  female   
215          216         1       1            Newell, Miss. Madeleine  female   
216          217         1       3             Honkanen, Miss. Eliina  female   
218          219         1       1              Bazzani, Miss. Albina  female   
445          446         1       1          Dodge, Master. Washington    male   

      Age  SibSp            Ticket      Fare Cabin Embarked  
0    22.0      1         A/5 21171    7.2500   NaN        S  
519  32.0      0            349242    7.8958   NaN        S  
521  22.0      0            349252    7.8958   NaN        S  
522   NaN      0              2624    7.2250   NaN        C  
524   NaN      0              2700    7.2292   NaN        C  
..    ...    ...               ...       ...   ...      ...  
546  19.0      1              2908   26.0000   NaN        S  
215  31.0      1             35273  113.2750   D36        C  
216  27.0      0  STON/O2. 3101283    7.9250   NaN        S  
218  32.0      0             11813   76.2917   D15        C  
445   4.0      0             33638   81.8583   A34        S  

[891 rows x 11 columns]

# Transpose Data

In [14]:
df.transpose()
#it converts columns into rows and rows into columns

0    \
PassengerId                        1   
Survived                           0   
Pclass                             3   
Name         Braund, Mr. Owen Harris   
Sex                             male   
Age                             22.0   
SibSp                              1   
Ticket                     A/5 21171   
Fare                            7.25   
Cabin                            NaN   
Embarked                           S   

                                                           1    \
PassengerId                                                  2   
Survived                                                     1   
Pclass                                                       1   
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...   
Sex                                                     female   
Age                                                       38.0   
SibSp                                                        1   
Ticket                                                PC 17599   
Fare                                                   71.2833   
Cabin                                                      C85   
Embarked                                                     C   

                                2    \
PassengerId                       3   
Survived                          1   
Pclass                            3   
Name         Heikkinen, Miss. Laina   
Sex                          female   
Age                            26.0   
SibSp                             0   
Ticket             STON/O2. 3101282   
Fare                          7.925   
Cabin                           NaN   
Embarked                          S   

                                                      3    \
PassengerId                                             4   
Survived                                                1   
Pclass                                                  1   
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Sex                                                female   
Age                                                  35.0   
SibSp                                                   1   
Ticket                                             113803   
Fare                                                 53.1   
Cabin                                                C123   
Embarked                                                S   

                                  4                 5    \
PassengerId                         5                 6   
Survived                            0                 0   
Pclass                              3                 3   
Name         Allen, Mr. William Henry  Moran, Mr. James   
Sex                              male              male   
Age                              35.0               NaN   
SibSp                               0                 0   
Ticket                         373450            330877   
Fare                             8.05            8.4583   
Cabin                             NaN               NaN   
Embarked                            S                 Q   

                                 6                               7    \
PassengerId                        7                               8   
Survived                           0                               0   
Pclass                             1                               3   
Name         McCarthy, Mr. Timothy J  Palsson, Master. Gosta Leonard   
Sex                             male                            male   
Age                             54.0                             2.0   
SibSp                              0                               3   
Ticket                         17463                          349909   
Fare                         51.8625                          21.075   
Cabin                            E46                             NaN   
Embarked                           S                    

# Shape and Reshape

In [15]:
df.shape

(891, 11)

In [16]:
import numpy as np

In [17]:
a1 = np.arange(10)
print('Array 1 \n', a1)

Array 1 
 [0 1 2 3 4 5 6 7 8 9]


In [18]:
a2 = np.arange(10).reshape(2,5)
print('Array 2 with 2 rows and 5 columns \n',a2)

Array 2 with 2 rows and 5 columns 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
a3 = np.arange(10).reshape(5,2)
print('Array 3 with 5 rows and 2 columns \n',a3)

Array 3 with 5 rows and 2 columns 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
d__f = df[['Name','Survived', 'Sex']]
d__f.head(11)

Name  Survived     Sex
0                             Braund, Mr. Owen Harris         0    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...         1  female
2                              Heikkinen, Miss. Laina         1  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)         1  female
4                            Allen, Mr. William Henry         0    male
5                                    Moran, Mr. James         0    male
6                             McCarthy, Mr. Timothy J         0    male
7                      Palsson, Master. Gosta Leonard         0    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1  female
9                 Nasser, Mrs. Nicholas (Adele Achem)         1  female
10                    Sandstrom, Miss. Marguerite Rut         1  female

In [22]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
1            PC 17599  71.2833   C85        C  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
..                ...      ...   ...      ...  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  
889            111369  30.0000  C148        C  
890            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

# Wide to Long

In [34]:
np.random.seed(123)
df = pd.DataFrame({"A1970" : {0 : "a", 1 : "b", 2 : "c"},
                   "A1980" : {0 : "d", 1 : "e", 2 : "f"},
                   "B1970" : {0 : 2.5, 1 : 1.2, 2 : .7},
                   "B1980" : {0 : 3.2, 1 : 1.3, 2 : .1},
                   "X"     : dict(zip(range(3), np.random.randn(3)))
                  })
df["id"] = df.index
df

A1970 A1980  B1970  B1980         X  id
0     a     d    2.5    3.2 -1.085631   0
1     b     e    1.2    1.3  0.997345   1
2     c     f    0.7    0.1  0.282978   2

In [39]:
pd.wide_to_long(df, ["A", "B"], i="id", j="year")

X  A    B
id year                  
0  1970 -1.085631  a  2.5
1  1970  0.997345  b  1.2
2  1970  0.282978  c  0.7
0  1980 -1.085631  d  3.2
1  1980  0.997345  e  1.3
2  1980  0.282978  f  0.1